### ISSUE TITLE
Currently not working (UI update?)

### ISSUE THREAD

**Issue by miffels** [Xeio/VoidRewardParser#11]
Hi,

seems like a recent update changed the UI and therefore the tool fails to detect items. It works fine on my prime parts inventory, but no longer on the rewards screen.

Best,
Michael

**Comment by vith** [comment]
The reward choices are still recognized at the rewards screen for me, but it's not detected as mission completion anymore, so it doesn't automatically pop up the window nor increment the counter for the item you chose when the end screen comes up.

**Comment by Xeio** [comment]
Yea, I've been meaning to check in a fix related to this, DE changed the text on the rewards screen so I need to change the text it uses to detect that and pop up.

**Comment by vith** [comment]
Oh wow, this is actually fixed! This whole time I thought I was on latest version already because the file properties had 1.0.0.0 as the version when I was still on Beta v0.8.0 😄

![2016-10-22_19-57-36](https://cloud.githubusercontent.com/assets/3265539/19623504/cce30268-9891-11e6-9d71-73da80c96750.png)

Anyway, thanks.
