### ISSUE TITLE
Doesn't seem to work now that War Within is out.

### ISSUE THREAD

**Issue by ghost** [Xeio/VoidRewardParser#14]
The application no longer seems to do much of anything now that War Within is out. It DOES detect if Warframe is open or not, but doesn't do anything beyond that. Even checking show all primes leaves the window empty, so maybe a database has changed, or something in the way Warframe works changed. The UI doesn't seem to have shifted, considering this tool parses the screen; so I'm assuming it's more of a back-end issue.

**Comment by Xeio** [comment]
Looks like the prime data isn't parsing anymore from Void's GitHub for whatever reason. Might have to look at why at a later point.

You can unzip this into your current directory (Warning: it will wipe out any inventory counts you have with mine since it's just an old PrimeData.data file I have plus a config change, might want to make a copy if you're worried about that). It just stops the tool from trying to fetch an updated list of primes/ducat values.

[VoidRewardParser.exe.zip](https://github.com/Xeio/VoidRewardParser/files/587442/VoidRewardParser.exe.zip)

**Comment by ghost** [comment]
Alright, I figured it was probably something like that. Thanks for the quick update, it's a really handy tool for keeping track of things.

**Comment by Xeio** [comment]
Looks like the actual prime data file is blank.

https://github.com/VoiDGlitch/WarframeData/issues/13

Hopefully VoidGlitch can figure it out whenever he has time (and DE hasn't made it completely hidden or anything). Till then the workraround is good enough.

**Comment by Xeio** [comment]
Oooo, now I feel bad because this issue got backlinked over there. GitHub is too clever.

**Comment by Xeio** [comment]
VoidGlitch appears to have fixed this, so you can go thank him.

Pushed v1.0.1 which is a little more tolerant to issues like this in the future. It will just keep using old prime data until a new retrieval is successful, rather than clearing all the data.
