### ISSUE TITLE
Setting up Visual Studio

### ISSUE THREAD

**Issue by WiiWalker** [Xeio/VoidRewardParser#3]
How do I get the namespaces "Windows.Globalization", "Windows.Media.Ocr" and "Windows.Storage.Streams" to work?

I've already installed .NET Framework 4.6, 4.6.1, 4.6.2 and the Windows 10 SDK but I can't get your project to work in Visual Studio. Any Clues? :(

**Comment by Xeio** [comment]
Are you running Windows 10? Those references exist in the Windows.winmd file.

I believe it should be located at C:\Program Files (x86)\Windows Kits\10\UnionMetadata\Windows.winmd.

I've heard someone else having problems with that reference being located when opening the project. I may have to look into manually fixing that HintPath in the .cjsproj file, since whatever Visual Studio puts in there by default doesn't seem to work.

**Comment by Xeio** [comment]
If you pull down the latest I changed the HintPath values to absolute paths. Not entirely sure that will fix the build issue though.

**Comment by WiiWalker** [comment]
That fixed it for me! The references are now recognized and the project builds successfully. Thanks for the update.
